### ISSUE TITLE
Licensing of slides

### ISSUE THREAD

**Issue by haesleinhuepf** [fractal-analytics-platform/fractal-demos#23]
Hi @jluethi ,

I just went through your slides linked from [this page](https://github.com/fractal-analytics-platform/fractal-demos/blob/main/demo-november-2022/fractal_demo_uzh.md). They are amazing and have a huge potential, also for teaching purposes. Unfortunately, there is no copyright statement. According to European law this means that these slides cannot be reused / reshared.

I was just wondering if you would mind resharing those slides with an open license. For example, on [https://f1000research.com/neubias](https://f1000research.com/neubias) you can share slides openly with the community [CC-BY](https://creativecommons.org/licenses/by/4.0/). This would allow others to reuse them.

Let me know what you think and thanks for making these slides available!

Best,
Robert

**Comment by jluethi** [comment]
Hey @haesleinhuepf 

Thanks for your interest. I briefly updated the slides (in minor ways) to make sure we could have them more broadly shared, still available under [this same link here](https://docs.google.com/presentation/d/1QGbkpdf9k58Gg-FH5U99vL8D9lmp2IJEiTJOwYL4OEY/edit#slide=id.g13f23a2e4da_0_395). If you need something of it for teaching or other purposes, feel free to use them (hopefully with an official license soon, with just written permission until then).

I had not put a license on them, because I did not consider them ready & relevant for general sharing yet. Fractal is approaching the point where we want to spread the word more broadly, but not ready for a broad user base just yet. But I do want our work to be in the open, so that's why they are already there. 

If you consider them useful already, then that's a good point towards putting an actual license on them. I've always enjoyed the slide decks you shared on twitter, I'll have a look at putting this slide deck (and maybe the Fractal poster we have) on the f1000 NEUBIAS page then (need to briefly read up on that). Thanks for linking to it! I hope I can get this done before the holidays start :)

Also, if you're looking through the demo repo: We just went live with our overview page for Fractal here: https://fractal-analytics-platform.github.io
It links to the documentation pages where available, e.g. the newly launched Fractal server doc page and the fractal-tasks-core docs :)
We're wrapping up work on release candidates for server & client and will hopefully soon (=> in early January) have a version we can share with a bit of confidence that it can be made to run in different places

**Comment by jluethi** [comment]
I've now shared the slides here with a CC-BY license: https://f1000research.com/slides/11-1557

And the Fractal poster we're presenting in early January can also be found here: https://f1000research.com/posters/11-1558

Thanks again for reaching out @haesleinhuepf ! I hope the material can be useful, would be curious to hear which parts you could use where :)

**Comment by haesleinhuepf** [comment]
What a wonderful Christmas 🎄 present. Big thanks @jluethi ! I presume I'll reuse it next semester when we talk about data management and large scale processing. I keep you posted!
