### ISSUE TITLE
Update demos after task refactor

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-demos#29]
This requires:
* https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/300
* https://github.com/fractal-analytics-platform/fractal-server/issues/534

**Comment by tcompa** [comment]
Still to do:
- [ ] Update pre-release server/client versions to 1.1.0 ones (when available)
- [ ] Update all examples that were skipped in #31 (where I am only updating `01_cardio_tiny_dataset` and `02_cardio_small`).

**Comment by jluethi** [comment]
I updated `01_cardio_tiny_dataset_with_import_export` and `user_specific_examples/01_CardiacDifferentiation_23wells` to 1.1.0 version.

Still to do:
- [ ] 03_cardio_multiplexing (currently broken due to multiplexing loading bug)
- [ ] 04_cardio_illumination_correction
- [ ] 05_cardio_plate_with_varying_wells
- [ ] 06_search_first_custom_cellpose
- [ ] 07_use_custom_task

Optional:
- [ ] Additional user_specific_examples

Also, when we update task versions, let's remember they are found in:
`local_user_setup.sh`, `manual_task_collection.sh` & in `setup_multi_user.sh` (all at 0.8.1 now). `manual_task_collection.sh` takes some extra checking when anything changes, because we do it in a manual way. But it's working again :)

**Comment by jluethi** [comment]
We also changed things in the most recent fractal client parts regarding dataset edit, with this PR https://github.com/fractal-analytics-platform/fractal/pull/439

=> the dataset edit commands also need to be adapted because the keywords changed to adapt those parameters.
That will make all of our examples break with the current 1.1.0a4 client version otherwise

```
fractal dataset edit --name "$DS_IN_NAME" -t image --read-only $PRJ_ID $DS_IN_ID
```

Should become:
```
fractal dataset edit --new-name "$DS_IN_NAME" --new-type image --make-read-only $PRJ_ID $DS_IN_ID
```

I'm not sure why this only came up in tests now. Where there other changes to task edit after https://github.com/fractal-analytics-platform/fractal/pull/439?

**Comment by tcompa** [comment]
> I'm not sure why this only came up in tests now. Where there other changes to task edit after https://github.com/fractal-analytics-platform/fractal/pull/439?

Yes, https://github.com/fractal-analytics-platform/fractal/pull/439. I now added it to the CHANGELOG, where it was somewhat hidden.

**Comment by jluethi** [comment]
The new example 06 now produces this nuclear segmentation within the organoids! 🎉

Awesome to see this running so smoothly on the example now. Great job @tcompa ! 👏🏻👏🏻

<img width="1813" alt="Screenshot 2023-03-16 at 18 15 34" src="https://user-images.githubusercontent.com/18033446/225699879-9f4cab0d-2d61-44ec-9ad7-3df54b53d36c.png">

**Comment by jluethi** [comment]
All the core examples (besides example 03 with the multiplexing channel bug) are now updated to 1.1.0 server release candidates & 0.9.0 tasks :)

I'm closing this and tracking progress on the user_specific_examples at https://github.com/fractal-analytics-platform/fractal-demos/issues/36
